# Generated by Django 4.0 on 2022-08-09 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_file_name', models.CharField(blank=True, max_length=100, null=True)),
                ('chucked_file', models.FileField(upload_to='zipped/%Y/%m/%d/')),
                ('_file_size', models.PositiveSmallIntegerField(default=0)),
                ('_file_url', models.URLField()),
                ('size_type', models.CharField(choices=[('KB', 'KB'), ('MB', 'MB')], max_length=3)),
                ('chunk_num', models.PositiveSmallIntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_file', to='auth.user')),
            ],
            options={
                'verbose_name_plural': 'Shredit',
                'ordering': ('-updated',),
            },
        ),
    ]
